language: objective-c
osx_image: xcode9.1
sudo: false

cache:
  - bundler
  - cocoapods

install:
  - bundle install --deployment
  - bundle exec pod --version
  - bundle exec pod repo update --verbose
  - bundle exec pod install

before_script:
  - set -o pipefail

script:
  - xcodebuild clean build test
  - workspace "RxLocation.xcworkspace"
  - scheme "RxLocation"
  - sdk "iphonesimulator11.1"
  - destination "platform=iOS Simulator,name=iPhone 8,OS=11.1"
  - configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c